#!/bin/bash
##########################################
# 2015 Mike Piekarski
# mike [-at-] automagine [-dot-] com
# Automagine, LLC
# --
# Greppable NMAP to CSV parser
# --
# A simple way to convert one or more gnmap files into a csv
# --
# Distribute, reuse, do whatever you want with this code.
###########################################

if [[ ${1} == "--help" || ${1} == "-h" ]]; then
    echo -e "Automagine GNMAP to CSV Parser Script.\n"
    echo "Usage for $(basename ${0}):"
    echo -e "\n\t${0} /path/to/file.gnmap /other/path/to/*.gnmap"
    exit 0
fi

echo '"IP","Hostname","Port","Protocol","Status","Service","Version","Service Detail"'
gawk '{
if ( NR < 1 ) {
  print "TEST"
}
  for( X=4; X<NF; X++) {
    if ( $X ~ /[0-9]{1,}\/open\// ) {
       if ( $X !~ /[\/,]$/ ) {
          if ( $(X+1) ~ /[\/,]$/ ) {
            $X=$X" "$(X+1)
          } else if ( $(X+2) ~ /[\/,]$/ ) {
            $X=$X" "$(X+1)" "$(X+2)
          } else if ( $(X+3) ~ /[\/,]$/ ) {
            $X=$X" "$(X+1)" "$(X+2)" "$(X+3)
          } else if ( $(X+4) ~ /[\/,]$/ ) {
            $X=$X" "$(X+1)" "$(X+2)" "$(X+3)" "$(X+4)
          } else if ( $(X+5) ~ /[\/,]$/ ) {
            $X=$X" "$(X+1)" "$(X+2)" "$(X+3)" "$(X+4)" "$(X+5)
          } else if ( $(X+6) ~ /[\/,]$/ ) {
            $X=$X" "$(X+1)" "$(X+2)" "$(X+3)" "$(X+4)" "$(X+5)" "$(X+6)
          }
       } {
            split($X, P, "/")
            gsub(/[\(\)]/,"", $3)
            gsub(/,/,"",$X)
            printf("\"%s\",\"%s\",\"%s\",\"%s\",\"%s\",\"%s\",\"%s\",\"%s\"\n", $2, $3, P[1], P[3], P[2], P[5], P[7], $X)
        }
    }
  }
}' $@ | sort -n | uniq
